services:
  client:
    build:
      context: ./client
      target: builder
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - server
  server:
    build:
      context: ./server
    container_name: server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
