services:
  client:
    build: ghcr.io/macrespo42/client:latest
    container_name: client
    ports:
      - 5173:5173
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    stdin_open: true
  server:
    build: ghcr.io/macrespo42/client:latest
    container_name: server
    ports:
      - 3000:3000
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    environment:
      - PORT=3000
