name: server ci

on:
  push:
    branches:
      - "main"
  paths:
    - "server/**"

jobs:
  styles:
    name: Style
    on: ubuntu-latest

  steps:
    - name: Check out code
      uses: action/checkout@v4
    
    - name: Setup node
      uses: action/setup-node@v4
      with:
        node-version: 22.12.0

    - name: Install dependencies
      run: |
        cd server
        npm install

    - name: Lint
      run: |
        cd server
        npm run lint
