name: Server CI

on:
  push:
    branches:
      - "main"
jobs:
  styles:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Lint
        run: |
          cd server
          npm run lint
